CREATE DATABASE AURICULARES;

CREATE TABLE AURICULARES.MARCAS (
    ID_MARCA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE AURICULARES.COLORES (
    ID_COLOR INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE AURICULARES.AURICULARES (
    ID_AURICULAR INT AUTO_INCREMENT PRIMARY KEY,
    MODELO VARCHAR(100) NOT NULL,
    PRECIO DECIMAL(10, 2) NOT NULL,
    RANGO_DE_ALCANCE_METROS INT NOT NULL,
    DURACION_BATERIA_HORAS INT NOT NULL,
    ID_COLOR INT,
    ID_MARCA INT,
    FOREIGN KEY (ID_COLOR) REFERENCES AURICULARES.COLORES(ID_COLOR)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
    FOREIGN KEY (ID_MARCA) REFERENCES AURICULARES.MARCAS(ID_MARCA)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE TABLE AURICULARES.TECNOLOGIAS (
    ID_TECNOLOGIA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE AURICULARES.AURICULAR_TECNOLOGIA (
    ID_AURICULAR INT,
    ID_TECNOLOGIA INT,
    PRIMARY KEY (ID_AURICULAR, ID_TECNOLOGIA),
    FOREIGN KEY (ID_AURICULAR) REFERENCES AURICULARES.AURICULARES(ID_AURICULAR)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (ID_TECNOLOGIA) REFERENCES AURICULARES.TECNOLOGIAS(ID_TECNOLOGIA)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- POR SI SE REQUIEREN EN EL FUTURO FILTRAR EN DB
CREATE INDEX IDX_MARCA_ID ON AURICULARES.MARCAS(ID_MARCA);
CREATE INDEX IDX_MARCA_NOMBRE ON AURICULARES.MARCAS(NOMBRE);

CREATE INDEX IDX_COLOR_ID ON AURICULARES.COLORES(ID_COLOR);
CREATE INDEX IDX_COLOR_NOMBRE ON AURICULARES.COLORES(NOMBRE);

CREATE INDEX IDX_AURICULARES_ID ON AURICULARES.AURICULARES(ID_AURICULAR);
CREATE INDEX IDX_AURICULARES_MODELO ON AURICULARES.AURICULARES(MODELO);
CREATE INDEX IDX_AURICULARES_PRECIO ON AURICULARES.AURICULARES(PRECIO);

CREATE INDEX IDX_TECNOLOGIA_ID ON AURICULARES.TECNOLOGIAS(ID_TECNOLOGIA);
CREATE INDEX IDX_TECNOLOGIA_NOMBRE ON AURICULARES.TECNOLOGIAS(NOMBRE);

CREATE INDEX IDX_AURICULAR_TECNOLOGIA_AUR ON AURICULARES.AURICULAR_TECNOLOGIA(ID_AURICULAR);
CREATE INDEX IDX_AURICULAR_TECNOLOGIA_TEC ON AURICULARES.AURICULAR_TECNOLOGIA(ID_TECNOLOGIA);