INSERT INTO AURICULARES.MARCAS (NOMBRE) VALUES ('SONY');
INSERT INTO AURICULARES.MARCAS (NOMBRE) VALUES ('BOSE');
INSERT INTO AURICULARES.MARCAS (NOMBRE) VALUES ('JBL');
INSERT INTO AURICULARES.MARCAS (NOMBRE) VALUES ('APPLE');
INSERT INTO AURICULARES.MARCAS (NOMBRE) VALUES ('SAMSUNG');

INSERT INTO AURICULARES.COLORES (NOMBRE) VALUES ('NEGRO');
INSERT INTO AURICULARES.COLORES (NOMBRE) VALUES ('PLATA');
INSERT INTO AURICULARES.COLORES (NOMBRE) VALUES ('AZUL');
INSERT INTO AURICULARES.COLORES (NOMBRE) VALUES ('GRIS ESPACIAL');
INSERT INTO AURICULARES.COLORES (NOMBRE) VALUES ('ROJO');
INSERT INTO AURICULARES.COLORES (NOMBRE) VALUES ('BLANCO');
INSERT INTO AURICULARES.COLORES (NOMBRE) VALUES ('BRONCE');

INSERT INTO AURICULARES.AURICULARES (MODELO, PRECIO, RANGO_DE_ALCANCE_METROS, DURACION_BATERIA_HORAS, ID_COLOR, ID_MARCA) VALUES ('SONY WH-1000XM4', 349.99, 10, 30, 1, 1);
INSERT INTO AURICULARES.AURICULARES (MODELO, PRECIO, RANGO_DE_ALCANCE_METROS, DURACION_BATERIA_HORAS, ID_COLOR, ID_MARCA) VALUES ('BOSE QUIETCOMFORT 35 II', 299.99, 10, 20, 2, 2);
INSERT INTO AURICULARES.AURICULARES (MODELO, PRECIO, RANGO_DE_ALCANCE_METROS, DURACION_BATERIA_HORAS, ID_COLOR, ID_MARCA) VALUES ('JBL TUNE 750BTNC', 99.99, 10, 15, 3, 3);
INSERT INTO AURICULARES.AURICULARES (MODELO, PRECIO, RANGO_DE_ALCANCE_METROS, DURACION_BATERIA_HORAS, ID_COLOR, ID_MARCA) VALUES ('APPLE AIRPODS MAX', 549.00, 10, 20, 4, 4);
INSERT INTO AURICULARES.AURICULARES (MODELO, PRECIO, RANGO_DE_ALCANCE_METROS, DURACION_BATERIA_HORAS, ID_COLOR, ID_MARCA) VALUES ('SAMSUNG GALAXY BUDS PRO', 199.99, 10, 18, 1, 5);
INSERT INTO AURICULARES.AURICULARES (MODELO, PRECIO, RANGO_DE_ALCANCE_METROS, DURACION_BATERIA_HORAS, ID_COLOR, ID_MARCA) VALUES ('SONY WF-1000XM3', 229.99, 10, 24, 1, 1);
INSERT INTO AURICULARES.AURICULARES (MODELO, PRECIO, RANGO_DE_ALCANCE_METROS, DURACION_BATERIA_HORAS, ID_COLOR, ID_MARCA) VALUES ('BOSE SOUNDSPORT', 149.99, 10, 5, 1, 2);
INSERT INTO AURICULARES.AURICULARES (MODELO, PRECIO, RANGO_DE_ALCANCE_METROS, DURACION_BATERIA_HORAS, ID_COLOR, ID_MARCA) VALUES ('JBL ENDURANCE PEAK', 99.99, 10, 28, 5, 3);
INSERT INTO AURICULARES.AURICULARES (MODELO, PRECIO, RANGO_DE_ALCANCE_METROS, DURACION_BATERIA_HORAS, ID_COLOR, ID_MARCA) VALUES ('APPLE AIRPODS PRO', 249.00, 10, 24, 6, 4);
INSERT INTO AURICULARES.AURICULARES (MODELO, PRECIO, RANGO_DE_ALCANCE_METROS, DURACION_BATERIA_HORAS, ID_COLOR, ID_MARCA) VALUES ('SAMSUNG GALAXY BUDS LIVE', 169.99, 10, 21, 7, 5);

INSERT INTO AURICULARES.TECNOLOGIAS (NOMBRE) VALUES ('BLUETOOTH 5.0');
INSERT INTO AURICULARES.TECNOLOGIAS (NOMBRE) VALUES ('CANCELACIÓN DE RUIDO');
INSERT INTO AURICULARES.TECNOLOGIAS (NOMBRE) VALUES ('RESISTENTE AL AGUA');
INSERT INTO AURICULARES.TECNOLOGIAS (NOMBRE) VALUES ('CARGA RÁPIDA');
INSERT INTO AURICULARES.TECNOLOGIAS (NOMBRE) VALUES ('ASISTENTE DE VOZ');

INSERT INTO AURICULARES.AURICULAR_TECNOLOGIA (ID_AURICULAR, ID_TECNOLOGIA) VALUES (1, 1), (1, 2), (1, 4); -- SONY WH-1000XM4
INSERT INTO AURICULARES.AURICULAR_TECNOLOGIA (ID_AURICULAR, ID_TECNOLOGIA) VALUES (2, 1), (2, 2); -- BOSE QUIETCOMFORT 35 II
INSERT INTO AURICULARES.AURICULAR_TECNOLOGIA (ID_AURICULAR, ID_TECNOLOGIA) VALUES (3, 1); -- JBL TUNE 750BTNC
INSERT INTO AURICULARES.AURICULAR_TECNOLOGIA (ID_AURICULAR, ID_TECNOLOGIA) VALUES (4, 1), (4, 2), (4, 4), (4, 5); -- APPLE AIRPODS MAX
INSERT INTO AURICULARES.AURICULAR_TECNOLOGIA (ID_AURICULAR, ID_TECNOLOGIA) VALUES (5, 1), (5, 3), (5, 5); -- SAMSUNG GALAXY BUDS PRO
INSERT INTO AURICULARES.AURICULAR_TECNOLOGIA (ID_AURICULAR, ID_TECNOLOGIA) VALUES (6, 1), (6, 2), (6, 3); -- SONY WF-1000XM3
INSERT INTO AURICULARES.AURICULAR_TECNOLOGIA (ID_AURICULAR, ID_TECNOLOGIA) VALUES (7, 1), (7, 3); -- BOSE SOUNDSPORT
INSERT INTO AURICULARES.AURICULAR_TECNOLOGIA (ID_AURICULAR, ID_TECNOLOGIA) VALUES (8, 1), (8, 3); -- JBL ENDURANCE PEAK
INSERT INTO AURICULARES.AURICULAR_TECNOLOGIA (ID_AURICULAR, ID_TECNOLOGIA) VALUES (9, 1), (9, 2), (9, 5); -- APPLE AIRPODS PRO
INSERT INTO AURICULARES.AURICULAR_TECNOLOGIA (ID_AURICULAR, ID_TECNOLOGIA) VALUES (10, 1), (10, 3); -- SAMSUNG GALAXY BUDS LIVE