SELECT A.ID_AURICULAR, A.MODELO, A.PRECIO, A.RANGO_DE_ALCANCE_METROS, A.DURACION_BATERIA_HORAS,
C.NOMBRE AS COLOR, M.NOMBRE AS MARCA
FROM AURICULARES.AURICULARES A
LEFT JOIN AURICULARES.MARCAS M ON M.ID_MARCA = A.ID_MARCA
LEFT JOIN AURICULARES.COLORES C ON C.ID_COLOR = A.ID_COLOR
ORDER BY A.ID_AURICULAR;

SELECT C.ID_COLOR, C.NOMBRE
FROM AURICULARES.COLORES C
ORDER BY C.ID_COLOR;

SELECT M.ID_MARCA, M.NOMBRE
FROM AURICULARES.MARCAS M
ORDER BY M.ID_MARCA;

SELECT C.NOMBRE AS COLOR, COUNT(A.ID_AURICULAR) AS CANTIDAD_AURICULARES
FROM AURICULARES.COLORES C
JOIN AURICULARES.AURICULARES A ON C.ID_COLOR = A.ID_COLOR
GROUP BY C.ID_COLOR, C.NOMBRE
HAVING COUNT(A.ID_AURICULAR) > 1;

SELECT M.NOMBRE AS MARCA, COUNT(A.ID_AURICULAR) AS CANTIDAD_AURICULARES
FROM AURICULARES.MARCAS M
JOIN AURICULARES.AURICULARES A ON M.ID_MARCA = A.ID_MARCA
GROUP BY M.ID_MARCA, M.NOMBRE
HAVING COUNT(A.ID_AURICULAR) > 1;

SELECT A.ID_AURICULAR, A.MODELO, A.PRECIO, A.RANGO_DE_ALCANCE_METROS, A.DURACION_BATERIA_HORAS, C.NOMBRE AS COLOR, M.NOMBRE AS MARCA
FROM AURICULARES.AURICULARES A
JOIN AURICULARES.COLORES C ON A.ID_COLOR = C.ID_COLOR
JOIN AURICULARES.MARCAS M ON A.ID_MARCA = M.ID_MARCA
WHERE A.ID_COLOR IN (
   SELECT C.ID_COLOR
	FROM AURICULARES.COLORES C
	JOIN AURICULARES.AURICULARES A ON C.ID_COLOR = A.ID_COLOR
	GROUP BY C.ID_COLOR, C.NOMBRE
	HAVING COUNT(A.ID_AURICULAR) > 1
)
AND A.ID_MARCA IN (
    SELECT M.ID_MARCA
	FROM AURICULARES.MARCAS M
	JOIN AURICULARES.AURICULARES A ON M.ID_MARCA = A.ID_MARCA
	GROUP BY M.ID_MARCA, M.NOMBRE
	HAVING COUNT(A.ID_AURICULAR) > 1
)
ORDER BY A.ID_AURICULAR;